compile :
	g++ -ggdb Plane.cpp test.cpp ../Controller/Controller.cpp ../EventBuffer/EventBuffer.cpp ../Interface/Interface.cpp ../Screen/Screen.cpp ../Semaphore/Semaphore.cpp ../Random/Random.cpp -std=c++11 -lpthread -lncurses -o test.o
